(function(){
'use strict';
var tooltipEl=null;var showTimeout=null;
function createTooltip(){if(tooltipEl)return tooltipEl;tooltipEl=document.createElement('div');tooltipEl.className='xaytheon-tooltip';tooltipEl.setAttribute('role','tooltip');tooltipEl.setAttribute('aria-hidden','true');tooltipEl.id='xaytheon-tooltip';document.body.appendChild(tooltipEl);return tooltipEl;}
function show(target){var text=target.getAttribute('data-tooltip');if(!text)return;var pos=target.getAttribute('data-tooltip-pos')||'top';var tip=createTooltip();tip.textContent=text;tip.setAttribute('aria-hidden','false');var rect=target.getBoundingClientRect();tip.style.top='';tip.style.left='';tip.classList.add('xaytheon-tooltip--visible');var tipRect=tip.getBoundingClientRect();var gap=8;switch(pos){case'bottom':tip.style.top=(rect.bottom+gap+window.scrollY)+'px';tip.style.left=(rect.left+rect.width/2-tipRect.width/2+window.scrollX)+'px';break;case'left':tip.style.top=(rect.top+rect.height/2-tipRect.height/2+window.scrollY)+'px';tip.style.left=(rect.left-tipRect.width-gap+window.scrollX)+'px';break;case'right':tip.style.top=(rect.top+rect.height/2-tipRect.height/2+window.scrollY)+'px';tip.style.left=(rect.right+gap+window.scrollX)+'px';break;default:tip.style.top=(rect.top-tipRect.height-gap+window.scrollY)+'px';tip.style.left=(rect.left+rect.width/2-tipRect.width/2+window.scrollX)+'px';}target.setAttribute('aria-describedby','xaytheon-tooltip');}
function hide(target){if(tooltipEl){tooltipEl.classList.remove('xaytheon-tooltip--visible');tooltipEl.setAttribute('aria-hidden','true');}if(target)target.removeAttribute('aria-describedby');}
function init(){document.addEventListener('mouseenter',function(e){var t=e.target.closest('[data-tooltip]');if(!t)return;clearTimeout(showTimeout);showTimeout=setTimeout(function(){show(t);},300);},true);document.addEventListener('mouseleave',function(e){var t=e.target.closest('[data-tooltip]');if(!t)return;clearTimeout(showTimeout);setTimeout(function(){hide(t);},100);},true);document.addEventListener('focusin',function(e){var t=e.target.closest('[data-tooltip]');if(t)show(t);},true);document.addEventListener('focusout',function(e){var t=e.target.closest('[data-tooltip]');if(t)hide(t);},true);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
window.XAYTHEON_TOOLTIP={show:show,hide:hide};
})();